[package]
name = "thormotion"
version = "0.1.3"
edition = "2021"

[lib]
name = "thormotion"
crate-type = ["cdylib"]
# "cdylib" is necessary to produce a shared library for Python to import from.

[dependencies]
tokio = { version = "*", features = ["full"] }
pyo3 = { version = "*", features = ["extension-module", "experimental-async"] }
rusb = "*"
phf = { version = "*", features = ["macros"] }

[build-dependencies]
csv = "*"
serde = { version = "*", features = ["derive"] }