[package]
name = "thormotion"
version = "0.3.0"
authors = ["Amelia Fraser-Dale"]
edition = "2024"
description = "A cross-platform motion control library for Thorlabs systems, written in Rust."
readme = "README.md"
repository = "https://github.com/MillieFD/thormotion"
license = "BSD-3"
keywords = ["thorlabs", "research", "automation", "robotics", "mechatronics"]
categories = ["hardware-support", "science", "science::robotics"]
exclude = ["build/"]
build = "build/build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "thormotion"
crate-type = ["cdylib", "rlib"]

[features]
default = []
format-built-files = []
extension-module = ["pyo3/extension-module"]

[dependencies]
pyo3 = { version = "*", features = ["experimental-async"] }
rusb = "*"
async-std = "*"
async-channel = "*"
thiserror = "*"
phf = "*"

[build-dependencies]
csv = "*"
serde = { version = "*", features = ["derive"] }
phf_codegen = "*"
