[package]
name = "thormotion"
version = "0.2.0"
edition = "2021"
description = "A cross-platform motion control library for Thorlabs systems, written in Rust."
keywords = ["thorlabs", "lab", "automation", "robot", "robotics"]
readme = "README.md"
license = "BSD-3"
repository = "https://github.com/MillieFD/thormotion"
authors = ["Amelia Fraser-Dale"]

[lib]
name = "thormotion"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "*", features = ["full"] }
pyo3 = { version = "*", features = ["extension-module", "experimental-async"] }
rusb = "*"
phf = { version = "*", features = ["macros"] }

[build-dependencies]
csv = "*"
serde = { version = "*", features = ["derive"] }