[package]
name = "thormotion"
version = "0.1.3"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
pyo3 = { version = "*", features = ["extension-module"] }
rusb = "*"
phf = { version = "*", features = ["macros"] }

[build-dependencies]
csv = "*"
serde = { version = "*", features = ["derive"] }