# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: release
      url: https://pypi.org/project/thormotion/${{ github.event.release.name }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
